import {proposalSchema} from './core.mjs';
export const OLLAMA_ENDPOINT='http://127.0.0.1:11434/api/chat';
export class OllamaProvider{
  constructor({fetchImpl=fetch,endpoint=OLLAMA_ENDPOINT}={}){const u=new URL(endpoint);if(u.protocol!=='http:'||u.hostname!=='127.0.0.1'||u.port!=='11434')throw new Error('OLLAMA_LOCALHOST_ONLY');this.fetch=fetchImpl;this.endpoint=endpoint;this.callLedger=new Map();}
  async createResponse({model,instructions,input,signal}){const response=await this.fetch(this.endpoint,{method:'POST',signal,headers:{'content-type':'application/json'},body:JSON.stringify({model,stream:false,think:false,format:proposalSchema,messages:[{role:'system',content:instructions},{role:'user',content:input}],options:{num_ctx:2048,num_predict:256,temperature:0}})});if(!response.ok)throw Object.assign(new Error('OLLAMA_ERROR'),{code:'PROVIDER'});const body=await response.json();const thinking=body?.message?.thinking;return {id:body?.created_at??null,output_text:body?.message?.content??'',metrics:{model:body?.model,created_at:body?.created_at,done:body?.done,done_reason:body?.done_reason,total_duration:body?.total_duration,load_duration:body?.load_duration,prompt_eval_count:body?.prompt_eval_count,prompt_eval_duration:body?.prompt_eval_duration,eval_count:body?.eval_count,eval_duration:body?.eval_duration,message_content_length:(body?.message?.content??'').length,thinking_present:typeof thinking==='string',thinking_length:typeof thinking==='string'?thinking.length:0}};}
}
export class OpenAIProvider{
  constructor({apiKey=process.env.OPENAI_API_KEY}={}){this.apiKey=apiKey;this.callLedger=new Map();}
  async createResponse({model,instructions,input,maxOutputTokens,signal}){if(!this.apiKey)throw Object.assign(new Error('OPENAI_API_KEY absent'),{code:'NO_CREDENTIAL'});const {default:OpenAI}=await import('openai');const client=new OpenAI({apiKey:this.apiKey});const response=await client.responses.create({model,instructions,input,max_output_tokens:maxOutputTokens,store:false,text:{format:{type:'json_schema',name:'goodagi_proposal',strict:true,schema:proposalSchema}}},{signal});return {id:response.id??null,output_text:response.output_text??'',metrics:{model:response.model??model,created_at:response.created_at??null,done:true,done_reason:null,total_duration:null,load_duration:null,prompt_eval_count:response.usage?.input_tokens??null,prompt_eval_duration:null,eval_count:response.usage?.output_tokens??null,eval_duration:null,message_content_length:(response.output_text??'').length,thinking_present:false,thinking_length:0}};}
}
export class TestProvider{
  constructor(){this.callLedger=new Map();}
  async createResponse({model,input}){const hostile=input.includes('XSS_TEST');const message=hostile?'<img src=x onerror=window.__xss=1>SAFE_TEXT_ONLY':`Wynik testowy dla: ${input.slice(0,80)}`;return {id:'test-response',output_text:JSON.stringify({kind:'proposal',action:'send_synthetic_message',object_id:'operator-channel',effect_id:'test-effect',payload:{value:null,message,amount:null}}),metrics:{model,done:true,done_reason:'stop',message_content_length:message.length,thinking_present:false,thinking_length:0}};}
}
