import test from 'node:test'; import assert from 'node:assert/strict'; import worker,{handle} from '../src/worker.mjs'; import {createOpenAIResponse} from '../src/providers/openai.mjs';
import {ControlBoundary} from '../lib/boundary.mjs'; import {invokeProposal,parseProposal} from '../lib/core.mjs'; import fs from 'node:fs';
const env={GOODAGI_REAL_PROVIDER_ENABLED:'false',ASSETS:{fetch:async()=>new Response('<h1>ui</h1>',{headers:{'content-type':'text/html'}})}};
const job={jobId:'pilot_1',clientLabel:'A',goal:'Assess a synthetic proposal',provider:'openai',model:'gpt-5.6-luna',confirmSyntheticOnly:true,agents:[{id:'a',role:'Analyst',instructions:'Analyze safely'}]};
async function call(path,body,headers={'content-type':'application/json'}){return worker.fetch(new Request('https://example.test'+path,{method:body?'POST':'GET',headers,body:body&&JSON.stringify(body)}),env)}
test('health is safe',async()=>{const r=await call('/api/health');const x=await r.json();assert.equal(x.status,'ok');assert.equal(x.real_provider_enabled,false);assert.equal('OPENAI_API_KEY' in x,false)});
test('validates valid job',async()=>assert.equal((await call('/api/validate',job)).status,200));
test('rejects authority and unknown fields',async()=>{let r=await call('/api/validate',{...job,principal_id:'bad'});assert.equal(r.status,400);r=await call('/api/validate',{...job,extra:true});assert.equal(r.status,400)});
test('rejects malformed, oversized, duplicate and too-many-agent input',async()=>{let r=await worker.fetch(new Request('https://example.test/api/validate',{method:'POST',headers:{'content-type':'application/json'},body:'{'}),env);assert.equal(r.status,400);r=await worker.fetch(new Request('https://example.test/api/validate',{method:'POST',headers:{'content-type':'application/json'},body:'x'.repeat(65537)}),env);assert.equal(r.status,413);r=await call('/api/validate',{...job,agents:[job.agents[0],{...job.agents[0]}]});assert.equal(r.status,400);r=await call('/api/validate',{...job,agents:Array.from({length:6},(_,i)=>({...job.agents[0],id:`a${i}`}))});assert.equal(r.status,400)});
test('disabled run makes no external calls',async()=>{const r=await call('/api/run',job);const x=await r.json();assert.equal(r.status,409);assert.equal(x.real_model_calls,0);assert.equal(x.termination_reason,'REAL_PROVIDER_DISABLED')});
test('injected provider crosses parser trusted identity and boundary once per agent',async()=>{let calls=0;const provider={callLedger:new Map(),createResponse:async()=>{calls++;return {output_text:JSON.stringify({kind:'proposal',action:'send_synthetic_message',object_id:'operator-channel',effect_id:'e'+calls,payload:{value:null,message:'safe',amount:null}})}}};const r=await handle(new Request('https://x/api/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...job,agents:[job.agents[0],{...job.agents[0],id:'b'}]})}),{...env,GOODAGI_REAL_PROVIDER_ENABLED:'true'},{provider});const x=await r.json();assert.equal(calls,2);assert.deepEqual(x.results.map(x=>x.decision),['ALLOW','ALLOW']);assert.equal(x.boundary.effect_count,2)});
test('OpenAI transport uses strict audited schema and store false',async()=>{let body;await createOpenAIResponse({env:{OPENAI_API_KEY:'test-key'},fetchImpl:async(_u,o)=>{body=JSON.parse(o.body);return new Response('{}')},instructions:'i',input:'x'});assert.equal(body.store,false);assert.equal(body.text.format.strict,true);assert.equal(body.text.format.schema.properties.kind.type,'string')});
test('provider errors and timeout fail closed with no effect',async()=>{for(const provider of [{callLedger:new Map(),createResponse:async()=>{throw Object.assign(new Error('x'),{code:'PROVIDER'})}},{callLedger:new Map(),createResponse:()=>new Promise(()=>{})}]){const b=new ControlBoundary({principals:[{id:'p',task_id:'t',budget:1,allowed_actions:['send_synthetic_message']}],objects:[{id:'operator-channel',value:'x',version:1}]});const out=await invokeProposal({provider,agent:{agent_id:'a',principal_id:'p',task_id:'t'},prompt:'x',boundary:b,model:'gpt-5.6-luna',limits:{max_model_calls_per_agent:1,max_output_tokens:1,max_proposal_bytes:99,timeout_ms:1}});assert.match(out.reason,/PROVIDER_ERROR_FAIL_CLOSED|TIMEOUT_FAIL_CLOSED/);assert.equal(b.effects.size,0)}});
test('authority injection and XSS remain data, secret sentinel leaks nowhere',async()=>{const bad='{"kind":"proposal","principal_id":"bad","action":"send_synthetic_message"}';assert.equal(parseProposal(bad).ok,false);const sentinel='TEST_SECRET_DO_NOT_LEAK_9f3e';const r=await worker.fetch(new Request('https://x/api/health'),{...env,OPENAI_API_KEY:sentinel});assert.equal((await r.text()).includes(sentinel),false);for(const f of ['public/index.html','public/app.js','public/styles.css','evidence/test-output.txt'])assert.equal(fs.readFileSync(f,'utf8').includes(sentinel),false);assert.match(fs.readFileSync('public/app.js','utf8'),/textContent/)});
test('headers and assets are protected',async()=>{const r=await worker.fetch(new Request('https://example.test/'),env);assert.match(r.headers.get('content-security-policy'),/default-src 'self'/);assert.equal(r.headers.get('access-control-allow-origin'),null)});
