import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {OllamaProvider,OLLAMA_ENDPOINT} from '../src/adapters/ollama.mjs';
import {proposalSchema,parseProposal,invokeProposal} from '../src/adapters/openai.mjs';
import {ControlBoundary} from '../src/boundary.mjs';

const STOP='{"kind":"stop","action":null,"object_id":null,"effect_id":null,"payload":null}';
const PROPOSAL='{"kind":"proposal","action":"inspect_object","object_id":"object-1","effect_id":"effect-1","payload":{"value":null,"message":null,"amount":null}}';
const SECRET='SECRET_THINKING_MARKER';
const agent={agent_id:'agent-1',principal_id:'trusted-principal',task_id:'trusted-task'};
const boundary=()=>new ControlBoundary({principals:[{id:'trusted-principal',task_id:'trusted-task',budget:3,allowed_actions:['inspect_object']}],objects:[{id:'object-1',version:1}],policyVersion:7});
const provider=(body,capture={})=>new OllamaProvider({fetchImpl:async(url,options)=>{capture.url=url;capture.request=JSON.parse(options.body);return {ok:true,json:async()=>body};}});
const response=(content,{message={},...extra}={})=>({model:'qwen3:0.6b',created_at:'response-1',message:{content,...message},done:true,done_reason:'stop',...extra});
const invoke=async(p,b=boundary(),limits={})=>({out:await invokeProposal({provider:p,agent,prompt:'inspect safely',boundary:b,limits:{timeout_ms:50,...limits},model:'qwen3:0.6b'}),boundary:b});

test('uses the localhost Ollama chat endpoint',()=>assert.equal(OLLAMA_ENDPOINT,'http://127.0.0.1:11434/api/chat'));
test('rejects a non-local Ollama endpoint',()=>assert.throws(()=>new OllamaProvider({endpoint:'https://example.test/api/chat'}),/OLLAMA_LOCALHOST_ONLY/));
test('sends non-streaming requests',async()=>{const c={};await provider(response(STOP),c).createResponse({model:'qwen3:0.6b',instructions:'i',input:'p'});assert.equal(c.request.stream,false);});
test('disables Ollama thinking in requests',async()=>{const c={};await provider(response(STOP),c).createResponse({model:'qwen3:0.6b',instructions:'i',input:'p'});assert.equal(c.request.think,false);});
test('sends the proposal schema as the response format',async()=>{const c={};await provider(response(STOP),c).createResponse({model:'qwen3:0.6b',instructions:'i',input:'p'});assert.deepEqual(c.request.format,proposalSchema);});
test('proposal schema requires every mediated field',()=>assert.deepEqual(proposalSchema.required,['kind','action','object_id','effect_id','payload']));
test('proposal payload schema rejects unknown fields',()=>assert.equal(proposalSchema.properties.payload.additionalProperties,false));
test('does not send tools to Ollama',async()=>{const c={};await provider(response(STOP),c).createResponse({model:'qwen3:0.6b',instructions:'i',input:'p'});assert.equal(Object.hasOwn(c.request,'tools'),false);});
test('uses bounded deterministic Ollama options',async()=>{const c={};await provider(response(STOP),c).createResponse({model:'qwen3:0.6b',instructions:'i',input:'p'});assert.deepEqual(c.request.options,{num_ctx:2048,num_predict:256,temperature:0});});
test('parses a valid STOP proposal',()=>assert.deepEqual(parseProposal(STOP),{ok:true,kind:'stop'}));
test('rejects invalid JSON proposals',()=>assert.equal(parseProposal('{').reason,'INVALID_JSON'));
test('rejects empty proposals',()=>assert.equal(parseProposal('').reason,'EMPTY_RESPONSE'));
test('rejects thinking text as a proposal',()=>assert.notEqual(parseProposal(SECRET).ok,true));
test('rejects model-supplied trusted identity fields',()=>assert.equal(parseProposal('{"kind":"proposal","action":"inspect_object","object_id":"object-1","effect_id":"effect-1","payload":{"value":null,"message":null,"amount":null},"principal_id":"attacker"}').reason,'FORBIDDEN_FIELD'));
test('mediates a valid proposal through the control boundary',async()=>{const {out,boundary:b}=await invoke(provider(response(PROPOSAL)));assert.equal(out.kind,'decision');assert.equal(out.decision.decision,'ALLOW');assert.equal(out.evidence.termination_reason,'MEDIATED_EFFECT');assert.equal(b.effects.size,1);});
test('binds trusted principal task request policy and server cost',async()=>{const {out}=await invoke(provider(response(PROPOSAL)));const r=out.evidence.trusted_request;assert.equal(r.principal_id,'trusted-principal');assert.equal(r.task_id,'trusted-task');assert.equal(r.request_id,'trusted:agent-1:0');assert.equal(r.policy_version,7);assert.equal(Object.hasOwn(r,'cost'),false);assert.equal(out.decision.budget_before-out.decision.budget_after,1);});
test('content STOP produces MODEL_STOP despite thinking',async()=>{const {out}=await invoke(provider(response(STOP,{message:{thinking:SECRET}})));assert.equal(out.kind,'stop');assert.equal(out.evidence.termination_reason,'MODEL_STOP');assert.deepEqual(out.evidence.parsed_proposal,{kind:'stop'});});
test('thinking text never becomes parsed proposal data',async()=>{const {out}=await invoke(provider(response(STOP,{message:{thinking:SECRET}})));assert.equal(JSON.stringify(out.evidence.parsed_proposal).includes(SECRET),false);});
test('serialized mediation evidence excludes thinking text',async()=>{const {out}=await invoke(provider(response(PROPOSAL,{message:{thinking:SECRET}})));const fixture=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'goodagi-')),'evidence.json');fs.writeFileSync(fixture,JSON.stringify({evidence:out.evidence,parsed:out.evidence.parsed_proposal,trusted:out.evidence.trusted_request,decision:out.decision}));const persisted=fs.readFileSync(fixture,'utf8');assert.equal(persisted.includes(SECRET),false);fs.rmSync(path.dirname(fixture),{recursive:true,force:true});});
test('thinking metadata retains only presence and exact length',async()=>{const {out}=await invoke(provider(response(STOP,{message:{thinking:'abcdef'}})));assert.equal(out.evidence.provider_metadata.thinking_present,true);assert.equal(out.evidence.provider_metadata.thinking_length,6);assert.equal(Object.hasOwn(out.evidence.provider_metadata,'thinking'),false);});
test('retains exact done metadata',async()=>{const {out}=await invoke(provider(response(STOP,{done:true,done_reason:'stop'})));assert.deepEqual({done:out.evidence.provider_metadata.done,done_reason:out.evidence.provider_metadata.done_reason},{done:true,done_reason:'stop'});});
test('retains exact evaluation metadata',async()=>{const {out}=await invoke(provider(response(STOP,{prompt_eval_count:3,eval_count:5,prompt_eval_duration:11,eval_duration:13})));assert.deepEqual(out.evidence.provider_metadata,{model:'qwen3:0.6b',created_at:'response-1',done:true,done_reason:'stop',total_duration:null,load_duration:null,prompt_eval_count:3,prompt_eval_duration:11,eval_count:5,eval_duration:13,message_content_length:STOP.length,thinking_present:false,thinking_length:0});});
test('timeout fails closed with zero effects even after a late response',async()=>{let resolve;const p=new OllamaProvider({fetchImpl:async()=>new Promise(r=>{resolve=r;})});const b=boundary();const out=await invokeProposal({provider:p,agent,prompt:'p',boundary:b,limits:{timeout_ms:5},model:'qwen3:0.6b'});assert.equal(out.reason,'TIMEOUT_FAIL_CLOSED');assert.equal(b.effects.size,0);resolve({ok:true,json:async()=>response(PROPOSAL)});await new Promise(r=>setTimeout(r,15));assert.equal(b.effects.size,0);});
test('Ollama response content is the sole proposal source',async()=>{const {out}=await invoke(provider(response(PROPOSAL,{message:{thinking:STOP}})));assert.equal(out.kind,'decision');assert.equal(out.evidence.parsed_proposal.action,'inspect_object');});
