import test from 'node:test'; import assert from 'node:assert/strict'; import {startBoundary,runAgent,sendRaw,snapshot,stopBoundary} from '../src/process-harness.mjs';
const config=(budget=2)=>({principals:['a','b','c'].map(id=>({id,task_id:`t-${id}`,budget,allowed_actions:['inspect_object']})),objects:[{id:'o',value:0,version:1}]});
const req=(principal,effect,extra={})=>({request_id:`${principal}-${effect}`,principal_id:principal,task_id:`t-${principal}`,effect_id:effect,action:'inspect_object',object_id:'o',policy_version:1,...extra});
async function withBoundary(options,fn){const b=await startBoundary(options);try{return await fn(b);}finally{await stopBoundary(b);}}
test('IPC: three OS processes isolate same client-visible effect id',async()=>withBoundary(config(),async b=>{const agents=await Promise.all(['a','b','c'].map(id=>runAgent(b.port,[req(id,'same')])));const s=await snapshot(b);assert.equal(new Set(agents.map(a=>a.pid)).size,3);assert.equal(s.effects,3);assert.deepEqual(agents.map(a=>a.results[0].result.decision),['ALLOW','ALLOW','ALLOW']);}));
test('IPC: eight concurrent retries create one commit and seven replays',async()=>withBoundary(config(),async b=>{const a=await runAgent(b.port,Array.from({length:8},(_,i)=>req('a','same',{request_id:`retry-${i}`})));const rs=a.results.map(x=>x.result);const s=await snapshot(b);assert.equal(rs.filter(x=>x.decision==='ALLOW').length,1);assert.equal(rs.filter(x=>x.decision==='REPLAY').length,7);assert.equal(s.effects,1);assert.equal(s.principals.find(p=>p.id==='a').remaining,1);}));
test('IPC: concurrent distinct effects respect budget one',async()=>withBoundary(config(1),async b=>{const a=await runAgent(b.port,[req('a','one'),req('a','two'),req('a','three')]);const rs=a.results.map(x=>x.result);assert.equal(rs.filter(x=>x.decision==='ALLOW').length,1);assert.equal(rs.filter(x=>x.reason==='BUDGET_EXHAUSTED').length,2);}));
test('IPC: malformed null denies and boundary stays alive',async()=>withBoundary(config(),async b=>{const bad=await sendRaw(b.port,null);assert.equal(bad.result.reason,'MALFORMED_REQUEST');const good=await sendRaw(b.port,req('a','after-null'));assert.equal(good.result.decision,'ALLOW');}));
test('IPC: host shell action denies without effect',async()=>withBoundary(config(),async b=>{const out=await sendRaw(b.port,req('a','shell',{action:'host_shell'}));const s=await snapshot(b);assert.equal(out.result.reason,'UNAUTHORIZED_ACTION');assert.equal(s.effects,0);}));
